# Generated by Django 6.1 on 2026-08-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_currency',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar')], default='BRL', max_length=3),
            preserve_default=False,
        ),
    ]
